增加使用 refresh_token 登录的函数
chyroc/go-aliyundrive pull request #24
Opened 2022-02-26 07:39 UTC by mingcheng

以及对应的用例测试

@TODO 分离保存 token 的方式，例如支持使用 redis 等中间件

2022-02-28 03:54 UTC, chyroc requested changes

2022-02-28 03:54 UTC, chyroc commented on .editorconfig
> +# http://editorconfig.org
remove `.editorconfig` file

2022-02-28 03:54 UTC, chyroc commented on api_auth_login.go
> +
remove this empty line

2022-02-28 03:54 UTC, chyroc commented on api_auth_login.go
> +	if err != nil {
`if err = r.cli.store.Set(ctx, token.Token()); err != nil {`

2022-02-28 03:54 UTC, chyroc commented on api_auth_login_test.go
> +	RefreshToken, empty := os.LookupEnv("REFRESH_TOKEN")
RefreshToken -> refreshToken

2022-02-28 03:54 UTC, chyroc commented on api_auth_refresh_token_test.go
> +	RefreshToken, empty := os.LookupEnv("REFRESH_TOKEN")
RefreshToken-> refreshToken

2022-02-28 09:44 UTC, mingcheng commented on .editorconfig
> +# http://editorconfig.org
editorconfig 是非常有用的，可以避免 IDE （以及 VSCode）格式化不一致的问题，相见 https://editorconfig.org/

2022-02-28 09:46 UTC, chyroc commented on .editorconfig
> +# http://editorconfig.org
go项目不需要这个

2022-02-28 09:56 UTC, mingcheng commented on .editorconfig
> +# http://editorconfig.org
> go项目不需要这个

这个和 Golang Project 无关的，真心建议加上同时了解下它

2022-03-03 03:43 UTC, chyroc commented on .editorconfig
> +# http://editorconfig.org
还是感觉需要去掉

2022-03-03 13:47 UTC, closed without merging